### ISSUE TITLE
Up ?

### ISSUE THREAD

**Issue by MrErne** [Skinz3/Symbioz-2.38#1]
Any update of the project ?

**Comment by happybydefault** [comment]
I hope this is for real! 😂

**Comment by Skinz3** [comment]
coming soon ;)

**Comment by MrErne** [comment]
I hope ;)

**Comment by The0nlyThe0ne** [comment]
When is soon ( ͡° ͜ʖ ͡°)? I honestly love your clean code, do you have any tips on how to update versions?

**Comment by MrErne** [comment]
up again ?

**Comment by DoobyChop** [comment]
It's dead, I suppose.

**Comment by nojo123** [comment]
Oh come on guys lets just wait. Its free so nothing to put pressure on. :-)

**Comment by DoobyChop** [comment]
How does that ass taste, nojo?

**Comment by nojo123** [comment]
Sorry?

**Comment by DoobyChop** [comment]
I'm serious, I was just asking how that ass tasted? Since that's what dutch kiddos like.

**Comment by nojo123** [comment]
If you're just here to insult me for no reason i suggest leaving Github and going back to your forum. There is no need to express your extra chromosome here.

**Comment by DoobyChop** [comment]
I'm not insulting you, why are you so mad? Did I hit a nerve? :(((

**Comment by nojo123** [comment]
Hmm alright, i'm not mad at all. Whats the deal with the first comment though? It does sound like you are butthurt about something starting with such a question. If you need any help with making friends consider social training. 
Best of luck, im ending the conversation here.

**Comment by DoobyChop** [comment]
Are you "ending" the conversation because you know I'm right? Or are you just ignorant? xoxox

**Comment by nojo123** [comment]
This is not meant for personal conversations, but for issues.

**Comment by Skinz3** [comment]
Dont throw my issues u_u

**Comment by tali1994** [comment]
Skinz3 gracias, haces buen trabajo se agradece espero con ansias nuevas actualizaciones estables. se respeta y se agradece su trabajo. Me subscribo
