### ISSUE TITLE
Error parsing GUID on log-in attempt (Non-negative number required)

### ISSUE THREAD

**Issue by Syndara** [Skinz3/Symbioz-2.38#10]
Hey people, I know this project isn't being worked on anymore, but hopefully someone can help me out with an issue I'm having.  I'm looking to start getting this ready for 2.40.

I have my world server online, and my auth server online.  When I go to connect from the client (as supplied from the readme.md file) I'm getting 

```
[TransitionClient] System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at SSync.IO.BigEndianReader.ReadBytes(Int32 n) in H:\Dofus Development\Symbioz-2.38\SSync\IO\BigEndianReader.cs:line 105
   at SSync.IO.CustomDataReader.ReadBytes(Int32 n) in H:\Dofus Development\Symbioz-2.38\SSync\IO\CustomDataReader.cs:line 219
   at SSync.Transition.TransitionClient.OnDataArrival(Byte[] buffer) in H:\Dofus Development\Symbioz-2.38\SSync\Transition\TransitionClient.cs:line 36
```

![image](https://user-images.githubusercontent.com/18456032/49774753-cc3a5f80-fcc3-11e8-9918-d2d1c4d04963.png)

The reader is taking in 0, 1, 217, 1 and underflowing the int returning for GUID.  I don't know enough about the packets being sent to figure out why this is happening, so I'm hoping one of you would be able to explain to me.  After debugging AuthServer it's definitely happening on a client login request.

Thanks!

**Comment by Skinz3** [comment]
What is the version of your client?

**Comment by Skinz3** [comment]
The GUID your talking about is probably the identifier of the transition message, world <-> auth.
https://github.com/Skinz3/Symbioz-2.38/blob/master/SSync/Transition/MessageRequest.cs
This is not a common error,  are you trying to connect with the 2.40 client?

**Comment by Syndara** [comment]
Hey thanks @Skinz3.  The version of the client is the version supplied on this github page.  https://1fichier.com/?fj0fiha9tb

Is there a different client needed since the source has been updated?

![image](https://user-images.githubusercontent.com/18456032/49907455-23ffd480-fe44-11e8-85fb-b8ab0c1e4117.png)


Sorry I don't know any French :(

**Comment by Skinz3** [comment]
Add me discord, Skinz#1128
