### ISSUE TITLE
Function Missing

### ISSUE THREAD

**Issue by Matspyder51** [Skinz3/Symbioz-2.38#3]
`CS1061	'IEnumerable<TObject>' ne contient pas de définition pour 'ConvertAll' et aucune méthode d'extension 'ConvertAll' acceptant un premier argument de type 'IEnumerable<TObject>' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	Symbioz.Core \Symbioz-2.38\Symbioz.Core\Extensions.cs	191	Actif
`

`var collection = obj.ConvertAll<TConvert>(converter);`

**Comment by Skinz3** [comment]
Vérifie que tu utilises le framework 4.5 pour le projet

**Comment by Skinz3** [comment]
@Matspyder51 Problème résolu?

**Comment by Skinz3** [comment]
@Matspyder51 J'ai fix le problème
