### ISSUE TITLE
Unable to connect to AuthServer

### ISSUE THREAD

**Issue by Neodecadente** [Skinz3/Symbioz-2.38#8]
I know this issue is pretty obvious, but I've searched everywhere in the code to find where my connection is failing. I have my local server up and running, three dbs with the same names as they came and connection still fails.

I modified connection config for Auth and World and no solution either. Lastly, I hardcoded ip and port into the Connect class and still no good news... 

If anybody could please help me, I'd be very grateful.

**Comment by pjouglet** [comment]
Check the auth.xml file,
the "DatabaseHost" field must be "127.0.0.1" (on a local server).
Then, check if "DatabaseUser", "DatabasePassword" & "DatabaseName" fit your MySQL connection settings.
And also, your MySQL server must listen on the 3306 port

**Comment by Neodecadente** [comment]
Thank you for your help, pjouglet! I've checked everyrthing you said, but it's still the same.

Something I noticed was that when I set the Symbioz.Auth component as the starting project, meaning that the program starts from there (sorry if that sounds confusing, I don't know the English name for that), Auth runs with no issues. Of course I can't get past the login screen in the client, but the program states that "Initialisation is completed". However Symbioz.World doesn't start.

![imagen](https://user-images.githubusercontent.com/17988681/42255725-2ce68bd2-7f1b-11e8-90d0-cdb6abc69dae.png)

**Comment by Skinz3** [comment]
Check : 
Your firewall
Your Dofus Configuration file

Give me screen from world server please

**Comment by Neodecadente** [comment]
Thanks for answering, Skinz3, I know you've walked away from dofus emulators path. Your help is very much appreciated.

`<WorldConfiguration>
  <UseCustomHost>False</UseCustomHost>
  <CustomHost></CustomHost>
  <ServerId>1</ServerId>
  <ServerName>Jiva</ServerName>
  <ServerType>1</ServerType>
  <SaveInterval>300</SaveInterval>
  <PerformBackup>True</PerformBackup>
  <StartMapId>156762120</StartMapId>
  <StartCellId>142</StartCellId>
  <StartKamas>0</StartKamas>
  <KamasRate>1</KamasRate>
  <DropsRate>1</DropsRate>
  <CraftRate>20</CraftRate>
  <StartLevel>1</StartLevel>
  <PlayDefaultCinematic>True</PlayDefaultCinematic>
  <WelcomeMessage>Welcome on server</WelcomeMessage>
  <MapKey>649ae451ca33ec53bbcbcc33becf15f4</MapKey>
  <ApLimit>12</ApLimit>
  <MpLimit>6</MpLimit>
  <Port>3306</Port>
  <ShowProtocolMessages>True</ShowProtocolMessages>
  <Host>127.0.0.1</Host>
  <SafeRun>True</SafeRun>
  <TransitionHost>127.0.0.1</TransitionHost>
  <TransitionPort>600</TransitionPort>
  <DatabaseHost>127.0.0.1</DatabaseHost>
  <DatabaseUser>root</DatabaseUser>
  <DatabasePassword></DatabasePassword>
  <DatabaseName>symbioz_world</DatabaseName>
</WorldConfiguration>
`

This is my world.xml config. I've checked my firewall and my client config also. No apparent issues there.

Your previous emulator works great. I have no idea why I can't make this one run u.u

**Comment by vikk27** [comment]
![1](https://user-images.githubusercontent.com/42148345/43725644-655df3fa-999d-11e8-8694-8f640230049b.JPG)
Help me please

**Comment by Skinz3** [comment]
@Neodecadente  Your world configuration is correct, can you send me your Dofus config file? Provide me also a screen of Symbioz.WorldServer executable
@vikk27 in database set the value for 'Banned' as 'True' or 'False' and not 0 or 1

**Comment by Bari77** [comment]
Bonjour @Skinz3,
J'ai dernièrement récupérer cette nouvelle version de ton émulateur. Je rencontre un léger problème lors de l'accès au serveur (world visiblement).
Je t'explique où j'en suis :

- J'arrive a me connecter au serveur auth sans soucis, j'ai un client dofus 2.34 (le 2.38 ne marchait pas car il attendait un 2.34);
- Si je met une valeur dans LastSelectedServerId, déjà a la connexion il me met un écran noir (même après la création d'un personnage);
- Si je n'ai aucun personnage de créer, j'arrive bien par défaut sur la création d'un personnage, mais celui-ci ne marche pas (après avoir appuyer sur le bouton "créer", celui-ci se grise, et l'ecran ne bouge plus, il reste sur la creation du personnage. Visiblement dans la BDD il crée bien le personnage, mais je n'arrive pas a me connecter sur le world.

Voici mon AuthConfig :
DatabaseHost = "127.0.0.1";
DatabaseUser = "root";
DatabasePassword = "root";
DatabaseName = "symbioz_auth";
Host = "127.0.0.1";
Port = 443;
ShowProtocolMessages = true;
SafeRun = false;
DofusProtocolVersion = 1709; // 2.34
TransitionHost = "127.0.0.1";
TransitionPort = 600;
VersionInstall = 1;
VersionTechnology = 1;
VersionBuildType = 0;
VersionMajor = 2;
VersionMinor = 34;
VersionPatch = 2;
VersionRelease = 2;
VersionRevision = 103887;

Voici mon WorldConfig :
DatabaseHost = "127.0.0.1";
DatabaseUser = "root";
DatabasePassword = "root";
DatabaseName = "symbioz_world";
Host = "127.0.0.1";
Port = 5555;
ShowProtocolMessages = true;
SafeRun = true;
StartMapId = 156762120;
StartCellId = 142;
ServerId = 1;
ServerName = "Jiva";
ServerType = 1;
TransitionHost = "127.0.0.1";
TransitionPort = 600;
SaveInterval = 300;
PerformBackup = true;
MapKey = "649ae451ca33ec53bbcbcc33becf15f4";
PlayDefaultCinematic = true;
UseCustomHost = false;
CustomHost = string.Empty;
StartLevel = 1;
StartKamas = 0;
KamasRate = 1;
DropsRate = 1;
CraftRate = 20;
WelcomeMessage = "Welcome on server";
ApLimit = 12;
MpLimit = 6;

Voici ma config dofus :
<entry key="connection.host">127.0.0.1</entry>
<entry key="connection.host.signature">AARBS1NGAAEAAACAG...</entry>
<entry key="connection.port">443</entry>

Puis le screen du world et auth :
![image](https://user-images.githubusercontent.com/20283367/52842031-185bb300-30fe-11e9-8aa6-4abf6a845c00.png)

Actuellement avec ce screen, le client vient de se connecter, mais a un ecran noir et ne voit rien (dans la BDD la valeur de LastSelectedServerId est a 1).

Merci de ton aide.
